### ISSUE TITLE
Shouldn't entity tracking range be taken into consideration for nearby entity tracking?

### ISSUE THREAD

**Issue by blastyman** [Samsuik/Blossom#1]
You could just backport: https://github.com/PaperMC/Paper/blob/master/patches/server/0995-Use-distance-map-to-optimise-entity-tracker.patch

**Comment by Samsuik** [comment]
I don't think there is a reason to backport the patch you linked. The patch I wrote already fixes the entity tracker iterating over all players in the world, instead it uses the chunk map to find players that have the chunk in their render distance.
